#Nombre del micro-servcio/Aplicación
spring.application.name=biblioteca

#Cambio puerto para ejecución
server.port=8081

#Ubicación de DB que nos conectaremos /Nombre DB
spring.datasource.url=jdbc:mysql://localhost:3306/libros-db

#Usuario por defecto MySQL, sin contraseña
spring.datasource.username=root
spring.datasource.password=

#Driver interprete para que MySQL entienda Spring y Spring a MySQL, cambia según DB a conectar
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Dialecto, lengua que ayuda a comunicarse con la DB
spring.jpa.database-platform=hibernate.dialect.MySQLDialect

#JPA
#Método parala creación de tablas
#update: si no existen las tablas, las crea y si existen, verifica si hay que hacer alguna modificación
spring.jpa.hibernate.ddl-auto=update

#Propiedades para mostrar la sentencia SQL que se ejecuta en el micro-servicio internamente
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Posterior a esto, se crea la DB con Xampp, se activa Apache, MySQL y se abre admin de MySQL.
#Se CyP el nombre de la DB